# Generated by Django 6.1 on 2026-08-11 04:11

import django.db.models.deletion
import documentos.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinica', '0001_initial'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoPaciente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('INFORME_MEDICO', 'Informe medico'), ('LABORATORIO', 'Resultado de laboratorio'), ('PLAN_TRATAMIENTO', 'Plan de tratamiento'), ('IMAGEN', 'Imagen clinica'), ('OTRO', 'Otro')], default='OTRO', max_length=24)),
                ('titulo', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, max_length=500, upload_to=documentos.models.ruta_documento_paciente)),
                ('nombre_original', models.CharField(blank=True, max_length=255)),
                ('tipo_mime', models.CharField(blank=True, max_length=120)),
                ('tamano_bytes', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('fecha_documento', models.DateField(blank=True, null=True)),
                ('origen', models.CharField(choices=[('APP', 'Aplicacion movil'), ('MEDICO', 'Medico'), ('SISTEMA', 'Sistema hospitalario')], default='APP', max_length=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de revision'), ('DISPONIBLE', 'Disponible'), ('RECHAZADO', 'Rechazado'), ('ARCHIVADO', 'Archivado')], default='PENDIENTE', max_length=16)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='clinica.consultaclinica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='pacientes.paciente')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-fecha_documento', '-creado_en'),
                'indexes': [models.Index(fields=['paciente', 'estado', '-creado_en'], name='documento_pac_estado_idx'), models.Index(fields=['tipo'], name='documento_tipo_idx')],
            },
        ),
    ]
