# Generated by Django 6.1 on 2026-08-11 16:32

import ML_core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionConsultaVoz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('LISTO', 'Listo para revisar'), ('PUBLICADO', 'Publicado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=16)),
                ('pregunta_actual', models.CharField(blank=True, max_length=300)),
                ('transcripcion', models.TextField(blank=True)),
                ('intervenciones', models.JSONField(blank=True, default=list)),
                ('datos_estructurados', models.JSONField(blank=True, default=ML_core.models.estructura_consulta_vacia)),
                ('ia_disponible', models.BooleanField(default=True)),
                ('mensaje_ia', models.CharField(blank=True, max_length=300)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('publicado_en', models.DateTimeField(blank=True, null=True)),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sesion_voz', to='clinica.consultaclinica')),
            ],
            options={
                'ordering': ('-creado_en',),
            },
        ),
    ]
