# Generated by Django 6.1 on 2026-08-11 04:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('CONSULTA', 'Consulta medica'), ('CONTROL', 'Control'), ('LABORATORIO', 'Laboratorio'), ('PROCEDIMIENTO', 'Procedimiento'), ('OTRO', 'Otro')], default='CONSULTA', max_length=20)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de confirmacion'), ('CONFIRMADA', 'Confirmada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('NO_ASISTIO', 'No asistio')], default='PENDIENTE', max_length=20)),
                ('origen', models.CharField(choices=[('HOSPITAL', 'Hospital'), ('FAMILIA', 'Declarada por la familia')], default='HOSPITAL', max_length=16)),
                ('especialidad', models.CharField(blank=True, max_length=120)),
                ('sede', models.CharField(default='Hospital del Nino San Borja', max_length=160)),
                ('consultorio', models.CharField(blank=True, max_length=80)),
                ('motivo', models.CharField(blank=True, max_length=240)),
                ('observaciones', models.TextField(blank=True)),
                ('confirmada_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('confirmada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_registradas', to=settings.AUTH_USER_MODEL)),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citas_como_medico', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='pacientes.paciente')),
            ],
            options={
                'ordering': ('inicio',),
                'indexes': [models.Index(fields=['paciente', 'inicio'], name='cita_paciente_inicio_idx'), models.Index(fields=['medico', 'inicio'], name='cita_medico_inicio_idx'), models.Index(fields=['estado', 'inicio'], name='cita_estado_inicio_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fin__isnull', True), ('fin__gt', models.F('inicio')), _connector='OR'), name='cita_fin_posterior_inicio')],
            },
        ),
    ]
