# Generated by Django 6.1 on 2026-08-11 04:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('historia_clinica', models.CharField(max_length=32, unique=True)),
                ('dni', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro'), ('N', 'No especificado')], default='N', max_length=1)),
                ('grupo_sanguineo', models.CharField(blank=True, max_length=8)),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=120)),
                ('nacionalidad', models.CharField(default='Peruana', max_length=80)),
                ('procedencia', models.CharField(blank=True, max_length=160)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('distrito', models.CharField(blank=True, max_length=100)),
                ('idioma_preferido', models.CharField(default='Español', max_length=40)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='PENDIENTE', max_length=16)),
                ('perfil_completo', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('apellidos', 'nombres'),
            },
        ),
        migrations.CreateModel(
            name='CuentaMovilPaciente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=80, unique=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACTIVA', 'Activa'), ('SUSPENDIDA', 'Suspendida')], default='PENDIENTE', max_length=16)),
                ('dispositivo', models.CharField(blank=True, max_length=120)),
                ('ultimo_acceso_en', models.DateTimeField(blank=True, null=True)),
                ('habilitada_en', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_paciente', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_movil', to='pacientes.paciente')),
            ],
            options={
                'verbose_name_plural': 'cuentas moviles de pacientes',
            },
        ),
        migrations.CreateModel(
            name='AsignacionMedica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('es_principal', models.BooleanField(default=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_medicas_realizadas', to=settings.AUTH_USER_MODEL)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_como_medico', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_medicas', to='pacientes.paciente')),
            ],
            options={
                'ordering': ('-activa', '-es_principal', '-fecha_inicio'),
            },
        ),
        migrations.CreateModel(
            name='TutorPaciente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('dni', models.CharField(blank=True, max_length=8)),
                ('parentesco', models.CharField(choices=[('MADRE', 'Madre'), ('PADRE', 'Padre'), ('TUTOR', 'Tutor legal'), ('OTRO', 'Otro')], max_length=16)),
                ('telefono_principal', models.CharField(max_length=20)),
                ('telefono_alternativo', models.CharField(blank=True, max_length=20)),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('distrito', models.CharField(blank=True, max_length=100)),
                ('persona_autorizada_adicional', models.CharField(blank=True, max_length=200)),
                ('preferencia_contacto', models.CharField(choices=[('LLAMADA', 'Llamada'), ('APP', 'Aplicacion'), ('CORREO', 'Correo electronico')], default='APP', max_length=16)),
                ('es_principal', models.BooleanField(default=False)),
                ('autorizado', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutores', to='pacientes.paciente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculos_tutor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-es_principal', 'apellidos', 'nombres'),
            },
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['apellidos', 'nombres'], name='paciente_nombre_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['estado'], name='paciente_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='asignacionmedica',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True), ('es_principal', True)), fields=('paciente',), name='un_medico_principal_activo'),
        ),
        migrations.AddConstraint(
            model_name='asignacionmedica',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('paciente', 'medico'), name='asignacion_medica_activa_unica'),
        ),
        migrations.AddConstraint(
            model_name='tutorpaciente',
            constraint=models.UniqueConstraint(condition=models.Q(('autorizado', True), ('es_principal', True)), fields=('paciente',), name='un_tutor_principal_autorizado'),
        ),
        migrations.AddConstraint(
            model_name='tutorpaciente',
            constraint=models.UniqueConstraint(condition=models.Q(('dni', ''), _negated=True), fields=('paciente', 'dni'), name='tutor_dni_unico_por_paciente'),
        ),
    ]
