# Generated by Django 6.1 on 2026-08-15 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_fecha_nacimiento_opcional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionmedica',
            name='cerrada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_medicas_cerradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asignacionmedica',
            name='cerrado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignacionmedica',
            name='motivo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='asignacionmedica',
            name='origen',
            field=models.CharField(choices=[('AUTOMATICA', 'Asignación automática'), ('MANUAL', 'Reasignación manual'), ('REEQUILIBRIO', 'Reequilibrio asistencial')], default='AUTOMATICA', max_length=16),
        ),
        migrations.AddIndex(
            model_name='asignacionmedica',
            index=models.Index(fields=['medico', 'activa', 'es_principal'], name='asig_med_carga_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionmedica',
            index=models.Index(fields=['paciente', '-creado_en'], name='asig_pac_hist_idx'),
        ),
    ]
