# Generated by Django 6.1 on 2026-08-11 04:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinica', '0001_initial'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_generico', models.CharField(max_length=160)),
                ('nombre_comercial', models.CharField(blank=True, max_length=160)),
                ('forma_farmaceutica', models.CharField(blank=True, max_length=80)),
                ('concentracion', models.CharField(blank=True, max_length=80)),
                ('codigo', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('nombre_generico', 'concentracion'),
                'constraints': [models.UniqueConstraint(fields=('nombre_generico', 'forma_farmaceutica', 'concentracion'), name='medicamento_presentacion_unica')],
            },
        ),
        migrations.CreateModel(
            name='Prescripcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_dosis', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unidad_dosis', models.CharField(max_length=30)),
                ('via', models.CharField(choices=[('ORAL', 'Oral'), ('INTRAVENOSA', 'Intravenosa'), ('SUBCUTANEA', 'Subcutanea'), ('INTRAMUSCULAR', 'Intramuscular'), ('TOPICA', 'Topica'), ('OTRA', 'Otra')], default='ORAL', max_length=20)),
                ('frecuencia_texto', models.CharField(max_length=160)),
                ('indicaciones', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ACTIVA', 'Activa'), ('PAUSADA', 'Pausada'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=16)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescripciones', to='clinica.consultaclinica')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescripciones', to='medicacion.medicamento')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescripciones_indicadas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescripciones', to='pacientes.paciente')),
                ('plan_tratamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescripciones', to='clinica.plantratamiento')),
            ],
            options={
                'ordering': ('-fecha_inicio', 'medicamento__nombre_generico'),
            },
        ),
        migrations.CreateModel(
            name='HorarioPrescripcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('intervalo_horas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('zona_horaria', models.CharField(default='America/Lima', max_length=64)),
                ('activo', models.BooleanField(default=True)),
                ('prescripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='medicacion.prescripcion')),
            ],
            options={
                'ordering': ('hora', 'intervalo_horas'),
            },
        ),
        migrations.CreateModel(
            name='DosisProgramada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('programada_para', models.DateTimeField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('TOMADA', 'Tomada'), ('TARDE', 'Tomada tarde'), ('OMITIDA', 'No tomada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=16)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dosis_programadas', to='medicacion.horarioprescripcion')),
                ('prescripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosis_programadas', to='medicacion.prescripcion')),
            ],
            options={
                'ordering': ('programada_para',),
            },
        ),
        migrations.CreateModel(
            name='ReporteDosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('respuesta', models.CharField(choices=[('TOMADA', 'Si la tomo'), ('TARDE', 'La tomo tarde'), ('NO_TOMADA', 'No la tomo')], max_length=16)),
                ('motivo_no_toma', models.CharField(blank=True, choices=[('OLVIDO', 'Olvido'), ('SIN_MEDICAMENTO', 'No habia medicamento'), ('MALESTAR', 'Malestar'), ('OTRO', 'Otro')], max_length=24)),
                ('observacion', models.CharField(blank=True, max_length=250)),
                ('ocurrida_en', models.DateTimeField()),
                ('origen', models.CharField(choices=[('APP', 'Aplicacion movil'), ('WEB', 'Portal web'), ('MEDICO', 'Medico')], default='APP', max_length=12)),
                ('reportada_en', models.DateTimeField(auto_now_add=True)),
                ('dosis_programada', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reporte', to='medicacion.dosisprogramada')),
                ('reportada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_dosis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-reportada_en',),
            },
        ),
        migrations.CreateModel(
            name='DiaHorarioPrescripcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miercoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sabado'), (6, 'Domingo')])),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='medicacion.horarioprescripcion')),
            ],
            options={
                'ordering': ('dia_semana',),
                'constraints': [models.UniqueConstraint(fields=('horario', 'dia_semana'), name='dia_unico_por_horario')],
            },
        ),
        migrations.AddIndex(
            model_name='prescripcion',
            index=models.Index(fields=['paciente', 'estado'], name='prescripcion_pac_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='horarioprescripcion',
            constraint=models.CheckConstraint(condition=models.Q(('hora__isnull', False), ('intervalo_horas__isnull', False), _connector='OR'), name='horario_hora_o_intervalo'),
        ),
        migrations.AddConstraint(
            model_name='horarioprescripcion',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True), ('hora__isnull', False)), fields=('prescripcion', 'hora'), name='horario_hora_activa_unica'),
        ),
        migrations.AddIndex(
            model_name='dosisprogramada',
            index=models.Index(fields=['estado', 'programada_para'], name='dosis_estado_fecha_idx'),
        ),
        migrations.AddConstraint(
            model_name='dosisprogramada',
            constraint=models.UniqueConstraint(fields=('prescripcion', 'programada_para'), name='dosis_programada_unica'),
        ),
    ]
