# Generated by Django 6.1 on 2026-08-11 04:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinica', '0001_initial'),
        ('documentos', '0001_initial'),
        ('medicacion', '0001_initial'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoSintoma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.SlugField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=240)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='ReporteSintomas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intensidad', models.CharField(choices=[('LEVE', 'Leve'), ('MODERADA', 'Moderada'), ('FUERTE', 'Fuerte')], max_length=12)),
                ('duracion', models.CharField(choices=[('MENOS_1_HORA', 'Menos de 1 hora'), ('ENTRE_1_6_HORAS', 'Entre 1 y 6 horas'), ('ENTRE_6_24_HORAS', 'Entre 6 y 24 horas'), ('MAS_24_HORAS', 'Mas de 24 horas')], max_length=24)),
                ('evolucion', models.CharField(choices=[('IGUAL', 'Igual'), ('MEJORO', 'Mejoro'), ('EMPEORO', 'Empeoro')], max_length=12)),
                ('observado_en', models.DateTimeField()),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('origen', models.CharField(choices=[('APP', 'Aplicacion movil'), ('WEB', 'Portal web'), ('MEDICO', 'Medico')], default='APP', max_length=12)),
                ('reportado_en', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_sintomas', to='pacientes.paciente')),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_sintomas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-observado_en', '-reportado_en'),
            },
        ),
        migrations.CreateModel(
            name='EventoSeguimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('MEDICACION', 'Medicacion'), ('SINTOMAS', 'Sintomas'), ('TRATAMIENTO', 'Tratamiento'), ('DOCUMENTO', 'Documento'), ('CONSULTA', 'Consulta'), ('OTRO', 'Otro')], max_length=16)),
                ('origen', models.CharField(choices=[('APP', 'Aplicacion movil'), ('WEB', 'Portal web'), ('MEDICO', 'Medico'), ('SISTEMA', 'Sistema')], max_length=12)),
                ('estado', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_SEGUIMIENTO', 'En seguimiento'), ('REVISADO', 'Revisado'), ('CUMPLIDO', 'Cumplido'), ('ALERTA', 'Alerta'), ('CERRADO', 'Cerrado')], default='RECIBIDO', max_length=20)),
                ('resumen', models.CharField(max_length=240)),
                ('detalle', models.TextField(blank=True)),
                ('ocurrido_en', models.DateTimeField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('consulta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evento_seguimiento', to='clinica.consultaclinica')),
                ('documento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evento_seguimiento', to='documentos.documentopaciente')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_seguimiento', to='pacientes.paciente')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_seguimiento_registrados', to=settings.AUTH_USER_MODEL)),
                ('reporte_dosis', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evento_seguimiento', to='medicacion.reportedosis')),
                ('reporte_sintomas', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evento_seguimiento', to='seguimiento.reportesintomas')),
            ],
            options={
                'ordering': ('-ocurrido_en', '-creado_en'),
            },
        ),
        migrations.CreateModel(
            name='SemaforoPaciente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nivel', models.CharField(choices=[('VERDE', 'Verde'), ('AMARILLO', 'Amarillo'), ('ROJO', 'Rojo')], max_length=12)),
                ('motivo', models.CharField(max_length=240)),
                ('origen', models.CharField(choices=[('REGLA', 'Regla automatica'), ('MEDICO', 'Evaluacion medica')], default='REGLA', max_length=12)),
                ('es_actual', models.BooleanField(default=True)),
                ('vigente_desde', models.DateTimeField(default=django.utils.timezone.now)),
                ('vigente_hasta', models.DateTimeField(blank=True, null=True)),
                ('determinado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semaforos_determinados', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_semaforo', to='pacientes.paciente')),
            ],
            options={
                'ordering': ('-vigente_desde',),
            },
        ),
        migrations.CreateModel(
            name='SintomaReportado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detalle', models.CharField(blank=True, max_length=160)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sintomas_reportados', to='seguimiento.reportesintomas')),
                ('sintoma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apariciones', to='seguimiento.catalogosintoma')),
            ],
        ),
        migrations.AddField(
            model_name='reportesintomas',
            name='sintomas',
            field=models.ManyToManyField(related_name='reportes', through='seguimiento.SintomaReportado', to='seguimiento.catalogosintoma'),
        ),
        migrations.CreateModel(
            name='AlertaSeguimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=60)),
                ('titulo', models.CharField(max_length=160)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Critica')], default='MEDIA', max_length=12)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_REVISION', 'En revision'), ('RESUELTA', 'Resuelta'), ('DESCARTADA', 'Descartada')], default='ABIERTA', max_length=16)),
                ('abierta_en', models.DateTimeField(auto_now_add=True)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('comentario_resolucion', models.TextField(blank=True)),
                ('asignada_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_seguimiento_asignadas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_seguimiento', to='pacientes.paciente')),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_seguimiento_resueltas', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='seguimiento.eventoseguimiento')),
            ],
            options={
                'ordering': ('-abierta_en',),
                'indexes': [models.Index(fields=['estado', 'prioridad', '-abierta_en'], name='alerta_estado_prior_idx'), models.Index(fields=['paciente', 'estado'], name='alerta_pac_estado_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='eventoseguimiento',
            index=models.Index(fields=['paciente', 'tipo', '-ocurrido_en'], name='evento_pac_tipo_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoseguimiento',
            index=models.Index(fields=['estado', '-ocurrido_en'], name='evento_estado_fecha_idx'),
        ),
        migrations.AddConstraint(
            model_name='semaforopaciente',
            constraint=models.UniqueConstraint(condition=models.Q(('es_actual', True)), fields=('paciente',), name='un_semaforo_actual_por_paciente'),
        ),
        migrations.AddConstraint(
            model_name='sintomareportado',
            constraint=models.UniqueConstraint(fields=('reporte', 'sintoma'), name='sintoma_unico_por_reporte'),
        ),
        migrations.AddIndex(
            model_name='reportesintomas',
            index=models.Index(fields=['paciente', '-observado_en'], name='sintoma_pac_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='reportesintomas',
            index=models.Index(fields=['intensidad', '-observado_en'], name='sintoma_int_fecha_idx'),
        ),
    ]
