# Generated by Django 6.1 on 2026-08-16 18:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
        ('pacientes', '0003_asignacionmedica_cerrada_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramacionQuimioterapia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(db_index=True)),
                ('turno', models.CharField(choices=[('T1', '08:00 - 11:00'), ('T2', '11:00 - 14:00'), ('T3', '14:00 - 17:30')], max_length=2)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('cama', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('CONFIRMADA', 'Confirmada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], db_index=True, default='PROGRAMADA', max_length=16)),
                ('origen', models.CharField(choices=[('AUTOMATICA', 'Agenda automática'), ('MANUAL', 'Programación manual'), ('AJUSTE', 'Ajuste administrativo')], max_length=12)),
                ('observaciones', models.TextField(blank=True)),
                ('confirmada_en', models.DateTimeField(blank=True, null=True)),
                ('cancelada_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelacion', models.CharField(blank=True, max_length=255)),
                ('recordatorio_estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('NO_REQUERIDO', 'No requerido')], db_index=True, default='PENDIENTE', max_length=16)),
                ('recordatorio_en', models.DateTimeField(blank=True, null=True)),
                ('recordatorio_observacion', models.CharField(blank=True, max_length=255)),
                ('cancelada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quimioterapias_canceladas', to=settings.AUTH_USER_MODEL)),
                ('cita', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programacion_quimioterapia', to='citas.cita')),
                ('confirmada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quimioterapias_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('programada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quimioterapias_programadas', to=settings.AUTH_USER_MODEL)),
                ('recordatorio_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordatorios_quimioterapia_marcados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('fecha', 'hora_inicio', 'cama'),
            },
        ),
        migrations.CreateModel(
            name='CambioProgramacionQuimioterapia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('accion', models.CharField(choices=[('CREADA', 'Creada'), ('AJUSTADA', 'Ajustada'), ('CONFIRMADA', 'Confirmada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('RECORDATORIO', 'Recordatorio actualizado')], max_length=16)),
                ('datos_anteriores', models.JSONField(blank=True, default=dict)),
                ('datos_nuevos', models.JSONField(blank=True, default=dict)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('realizada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_programacion_quimioterapia', to=settings.AUTH_USER_MODEL)),
                ('programacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='clinica_dia.programacionquimioterapia')),
            ],
            options={
                'ordering': ('-creado_en',),
            },
        ),
        migrations.CreateModel(
            name='SolicitudQuimioterapia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('dni', models.CharField(db_index=True, max_length=8)),
                ('nombre_completo_importado', models.CharField(max_length=241)),
                ('historia_clinica_importada', models.CharField(blank=True, max_length=32)),
                ('fecha_nacimiento_importada', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('procedencia', models.CharField(max_length=160)),
                ('diagnostico', models.CharField(blank=True, max_length=240)),
                ('protocolo', models.CharField(blank=True, max_length=240)),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], db_index=True, default='MEDIA', max_length=8)),
                ('fecha_preferida', models.DateField(blank=True, db_index=True, null=True)),
                ('hora_preferida', models.TimeField(blank=True, null=True)),
                ('duracion_minutos', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(210)])),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de programación'), ('PROGRAMADA', 'Programada'), ('CONFIRMADA', 'Confirmada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], db_index=True, default='PENDIENTE', max_length=16)),
                ('origen', models.CharField(choices=[('IMPORTACION', 'Importación XLSX'), ('MANUAL', 'Registro manual')], max_length=16)),
                ('codigo_externo', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('lote_importacion', models.UUIDField(blank=True, db_index=True, null=True)),
                ('fila_importacion', models.PositiveIntegerField(blank=True, null=True)),
                ('huella_importacion', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_quimioterapia_creadas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_quimioterapia', to='pacientes.paciente')),
            ],
            options={
                'ordering': ('-prioridad', 'fecha_preferida', 'creado_en'),
            },
        ),
        migrations.AddField(
            model_name='programacionquimioterapia',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programaciones', to='clinica_dia.solicitudquimioterapia'),
        ),
        migrations.AddIndex(
            model_name='solicitudquimioterapia',
            index=models.Index(fields=['estado', 'prioridad', 'fecha_preferida'], name='quim_sol_pendiente_idx'),
        ),
        migrations.AddConstraint(
            model_name='solicitudquimioterapia',
            constraint=models.CheckConstraint(condition=models.Q(('duracion_minutos__gte', 15), ('duracion_minutos__lte', 210)), name='quim_sol_duracion_rango'),
        ),
        migrations.AddIndex(
            model_name='programacionquimioterapia',
            index=models.Index(fields=['fecha', 'turno', 'estado'], name='quim_prog_agenda_idx'),
        ),
        migrations.AddIndex(
            model_name='programacionquimioterapia',
            index=models.Index(fields=['recordatorio_estado', 'fecha'], name='quim_prog_record_idx'),
        ),
        migrations.AddConstraint(
            model_name='programacionquimioterapia',
            constraint=models.CheckConstraint(condition=models.Q(('cama__gte', 1), ('cama__lte', 8)), name='quim_prog_cama_rango'),
        ),
        migrations.AddConstraint(
            model_name='programacionquimioterapia',
            constraint=models.CheckConstraint(condition=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='quim_prog_horas_validas'),
        ),
        migrations.AddConstraint(
            model_name='programacionquimioterapia',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'CANCELADA'), _negated=True), fields=('fecha', 'turno', 'cama'), name='quim_prog_slot_unico'),
        ),
        migrations.AddConstraint(
            model_name='programacionquimioterapia',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'CANCELADA'), _negated=True), fields=('solicitud',), name='quim_prog_solicitud_activa'),
        ),
    ]
