# Generated by Django 6.1 on 2026-08-11 04:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaClinica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(default='Consulta medica', max_length=180)),
                ('resumen', models.TextField(blank=True)),
                ('origen', models.CharField(choices=[('MANUAL', 'Registro manual'), ('VOZ', 'Dictado por voz')], default='MANUAL', max_length=12)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=16)),
                ('iniciada_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('completada_en', models.DateTimeField(blank=True, null=True)),
                ('anulada_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cita', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consulta_clinica', to='citas.cita')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas_medicas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='pacientes.paciente')),
            ],
            options={
                'ordering': ('-iniciada_en',),
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_cie10', models.CharField(blank=True, max_length=16)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_diagnostico', models.DateField(default=django.utils.timezone.localdate)),
                ('es_principal', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('RESUELTO', 'Resuelto'), ('DESCARTADO', 'Descartado')], default='ACTIVO', max_length=16)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos_registrados', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='pacientes.paciente')),
            ],
            options={
                'ordering': ('-es_principal', '-fecha_diagnostico'),
            },
        ),
        migrations.CreateModel(
            name='PlanTratamiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='Plan de tratamiento', max_length=180)),
                ('indicacion_general', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('VIGENTE', 'Vigente'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=16)),
                ('vigente_desde', models.DateField(default=django.utils.timezone.localdate)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('consulta_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_generados', to='clinica.consultaclinica')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_tratamiento_indicados', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_tratamiento', to='pacientes.paciente')),
            ],
            options={
                'ordering': ('-vigente_desde', '-creado_en'),
            },
        ),
        migrations.CreateModel(
            name='ItemPlanTratamiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('TRATAMIENTO', 'Tratamiento indicado'), ('MEDICACION', 'Medicacion indicada'), ('CUIDADO_CASA', 'Indicaciones para casa'), ('EXAMEN', 'Examen solicitado'), ('CONTROL', 'Proximo control'), ('OTRO', 'Otro')], max_length=20)),
                ('titulo', models.CharField(max_length=160)),
                ('descripcion', models.TextField()),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinica.plantratamiento')),
            ],
            options={
                'ordering': ('orden', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SeccionConsulta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('MOTIVO', 'Motivo de consulta'), ('EVOLUCION', 'Evolucion clinica'), ('TRATAMIENTO', 'Tratamiento indicado'), ('MEDICACION', 'Medicacion indicada'), ('INDICACIONES', 'Indicaciones para casa'), ('PROXIMO_CONTROL', 'Proximo control'), ('OTRO', 'Otro')], max_length=24)),
                ('titulo', models.CharField(max_length=160)),
                ('contenido', models.TextField(blank=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='clinica.consultaclinica')),
            ],
            options={
                'ordering': ('orden', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ItemSeccionConsulta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('etiqueta', models.CharField(blank=True, max_length=140)),
                ('descripcion', models.TextField()),
                ('valor', models.CharField(blank=True, max_length=180)),
                ('unidad', models.CharField(blank=True, max_length=40)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinica.seccionconsulta')),
            ],
            options={
                'ordering': ('orden', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='consultaclinica',
            index=models.Index(fields=['paciente', '-iniciada_en'], name='consulta_pac_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='consultaclinica',
            index=models.Index(fields=['estado'], name='consulta_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnostico',
            index=models.Index(fields=['paciente', 'estado'], name='diagnostico_pac_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='diagnostico',
            constraint=models.UniqueConstraint(condition=models.Q(('es_principal', True), ('estado', 'ACTIVO')), fields=('paciente',), name='un_diagnostico_principal_activo'),
        ),
        migrations.AddIndex(
            model_name='plantratamiento',
            index=models.Index(fields=['paciente', 'estado'], name='plan_pac_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='seccionconsulta',
            constraint=models.UniqueConstraint(fields=('consulta', 'tipo'), name='seccion_tipo_unico_por_consulta'),
        ),
    ]
